# src/lang_eng.py

TEXTS = {
    "nav_home": "🏠 Home",
    "nav_coach": "🔑 Coach",
    "nav_sessions": "📅 Sessions",
    "nav_admin": "👥 Account",
    # General UI
    "lbl_hello": "Hello",
    "lbl_member": "Member",
    "lbl_total": "Total",
    "lbl_date": "Date",
    "lbl_time": "Time",
    "lbl_location": "Location",
    "lbl_wind": "Wind",
    "lbl_weather": "Weather",
    "lbl_unknown_date": "Unknown date",
    "lbl_system": "System",
    "lbl_me": "(Me)",
    "lbl_guest_coach": "Guest Coach",
    # Profile & Settings
    "lbl_profile_info": "**Manage your personal settings, change interface language, and update security.**",
    "lbl_account_details": "Account Details",
    "lbl_full_name": "Full Name",
    "lbl_role": "Access Level / Role",
    "lbl_lang_selector": "🌐 Select System Language",
    "lbl_session": "Session",
    "lbl_security": "Settings & Security",
    "lbl_pwd_expander": "🔑 Change Password",
    "lbl_new_pwd": "New Password",
    "lbl_conf_pwd": "Confirm New Password",
    "lbl_gdpr_expander": "🔒 Data Privacy & GDPR",
    "lbl_gdpr_header": "GDPR Data Export",
    "lbl_gdpr_text": "Under the GDPR, you have the right to download all personal data stored about you.",
    "lbl_gdpr_future": "*(Future feature: Generates an encrypted JSON file containing your profile, RSVP, and history data)*",
    "btn_pwd_update": "Update Password",
    "btn_gdpr_export": "📦 Request GDPR Data Export",
    "btn_logout": "Log out of Coach Engine",
    # Admin & Logs
    "tab_access_logs": "📋 Access Logs",
    "tab_user_management": "👥 User Management",
    "tab_system_settings": "⚙️ System Settings",
    "tab_profile": "👤 My Profile",
    "tab_stats": "📊 Stats",
    "lbl_unknown_time": "Unknown time",
    "lbl_modified": "modified",
    "btn_create_user": "➕ Create New User",
    "lbl_temp_pwd": "Temporary password (min 6 chars)",
    "lbl_first_name": "First name",
    "role_member": "Member",
    "role_coach": "Coach",
    "role_admin": "Admin",
    "lbl_system_role": "System role",
    "btn_invite_user": "Invite and create account",
    "btn_reset_pwd": "🔑 Reset password for member",
    "lbl_select_user": "Select member to reset",
    "lbl_new_temp_pwd": "New temporary password",
    "btn_forced_reset": "Forced password change",
    "msg_admin_warning": "**Here you can cancel or reactivate the selected session.** This immediately updates what is displayed on the participant home screen.\n\n* 🎈 **Balloons** confirm when saved! 🥳",
    "lbl_status": "Status:",
    "lbl_canceled": "🔴 CANCELED",
    "lbl_active": "🟢 ACTIVE",
    "btn_activate": "✅ Activate session",
    "btn_cancel": "🚫 Cancel session",
    "btn_manage": "⚙️ Manage",
    "err_no_data": "Could not read session data.",
    "err_status_update": "Could not update status: ",
    # Stats & Weather Heroes
    "msg_stats_intro": "📊 This leaderboard tracks the official weather heroes based on completed sessions and historical weather data.",
    "msg_no_stats": "No active members or stats found right now.",
    "lbl_my_status": "Your Training Status",
    "lbl_entire_squad": "The Entire Squad",
    "lbl_leader_small": "led",
    "lbl_to": "to",
    "lbl_under_10": "Sessions under -10°C",
    "lbl_over_20": "Sessions over +20°C",
    "lbl_bad": "Bad weather",
    "lbl_windy": "Windy sessions",
    "lbl_dark": "Dark sessions",
    "lbl_climate_range": "Climate range",
    "rank_elite_veteran": "🎖️ Elite Veteran",
    "rank_heavy_hitter": "🏋️‍♂️ Heavy Hitter",
    "rank_active_member": "🏃‍♂️ Active Member",
    "rank_recruit": "🔰 Recruit",
    "lbl_total_sessions": "Total Sessions",
    "lbl_bad_weather": "Bad",
    "lbl_storm": "Storm",
    "lbl_leader_caps": "Lead",
    # Architect & Workout
    "msg_architect_info": "**Build the workout structure.** Choose a protocol to let the engine randomize and match exercises based on weather, geography, and levels.",
    "lbl_protocol": "Protocol",
    "lbl_levels": "Levels (Session Architecture)",
    "lvl_1_label": "🏃‍♂️ Level 1: Monostructural",
    "lvl_2_label": "🏋️‍♂️ Level 2: Hybrid Structure",
    "lvl_3_label": "🏁 Level 3: Multi-Segment / 'The Gauntlet'",
    "lbl_equip_filter": "Equipment filter",
    "lbl_bodyweight_only": "🤸‍♂️ Bodyweight only",
    "lbl_manual_notes": "📝 Manual Notes",
    "ph_manual_notes": "Enter session structure or instructions here...",
    "btn_generate_suggestion": "🚀 Generate Suggestion",
    "btn_save_manual": "💾 Save manual session / note",
    "lbl_architect_summary": "Architect Summary",
    "lbl_duration": "Duration",
    "lbl_stations": "Stations",
    "lbl_rounds": "Rounds",
    "lbl_work_sec": "Work (s)",
    "lbl_blocks": "Blocks",
    "lbl_rest_sec": "Rest (s)",
    "lbl_minutes": "Minutes",
    "msg_no_session": "No session generated yet.",
    "lbl_todays_session": "Today's session",
    "lbl_simplified_exercise": "💡 Simplified exercise",
    "lbl_coach_notes": "📝 Coach Notes",
    "lbl_equipment_list": "🎒 🪵 Equipment List 🪨 ⛓️",
    "btn_publish": "Publish & Save to Squad",
    "lbl_select_session": "Select session to manage",
    "msg_legend_details": (
        "✅ **Empty** – Ready to plan!\n"
        "🏗️ **Workout** – Program created.\n"
        "🎒 **Gear** – Material ordered.\n"
        "📝 **Notes** – Manual notes saved.\n"
        "📚 **Combo** – Mixed contents.\n"
        "🚫 **Canceled** – Session is inactive."
    ),
    "msg_suggestion_generated": "💡 Suggestion generated based on current weather!",
    "msg_architect_thinking": "🧠 Architect is analyzing environmental data...",
    # Gear Bank
    "msg_gear_info": "**Manage portable equipment.** Choose equipment to pack. Independent or complement to session.",
    "lbl_standard": "Standard",
    "msg_save_confirmation": "🎈 Balloons confirm that your changes are saved! 🥳",
    "btn_lock_gear": "Lock equipment order",
    # Exercises
    "msg_bank_info": "**Global exercise library.** Used by the Architect.",
    "btn_contribute_exercise": "➕ Contribute new exercise",
    "lbl_exe_name": "Exercise name",
    "lbl_instructions": "Instructions",
    "lbl_equipment": "Equipment",
    "lbl_level": "Level",
    "lbl_standing": "Standing",
    "lbl_rain": "Rain",
    "lbl_hill": "Hill",
    "lbl_wall": "Wall/Stairs",
    "btn_save_bank": "Save to bank",
    "msg_saved": "Saved!",
    "msg_bank_empty": "Bank is empty or data could not be fetched.",
    "lbl_bodyweight": "Bodyweight",
    "lbl_search_exe": "Search exercise:",
    "btn_clear_search": "❌ Clear search",
    "lbl_showing": "Showing",
    "lbl_exercises": "exercises",
    # Home & Sessions
    "lbl_good_morning": "Good morning",
    "lbl_good_evening": "Good evening",
    "msg_no_sessions": "No upcoming sessions planned right now.",
    "lbl_session_canceled": "SESSION CANCELED",
    "msg_home_instructions": "**Next workout!** For all sessions, check the **Sessions** tab.",
    "msg_session_admin_info": "Manage participation, view history, or schedule new sessions.",
    "tab_upcoming": "📅 Upcoming",
    "tab_history": "📜 History",
    "tab_create_session": "➕ Create New Session",
    "msg_no_upcoming": "No scheduled sessions right now.",
    "lbl_registered": "registered",
    "lbl_participants": "Participants",
    "lbl_cant_make_it": "Can't make it",
    "msg_no_history": "No history found.",
    "lbl_who_was_there": "Who was there",
    "btn_save_session": "Save Session",
    "msg_session_created": "Session created!",
    "btn_attending": "✅ Attending",
    "btn_take_crown": "👑 Take the Crown",
    "btn_cant_make_it": "❌ Can't make it",
    "btn_step_down": "👑👋 Step Down",
    "msg_leader_secured": "✅ **The scepter is secured!**",
    "msg_leader_needed": "⚠️ **The throne is empty!** Who will step up to lead?",
    "btn_register_buddy": "➕ Register a Buddy",
    "btn_book_buddy": "👥 Book Buddy",
    "placeholder_select_member": "Select member...",
    "lbl_attending": "Attending",
    "lbl_not_coming": "Can't make it",
    "msg_no_registrations": "No registrations yet.",
    # Landing/Login
    "msg_landing_welcome": "**Elittruppen in Rönninge.** Community training, completely free.",
    "msg_landing_details": "Everyone is welcome. Come as you are.",
    "lbl_schedule": "**Wednesdays** 18:00 \n\n**Sundays** 09:30",
    "lbl_login": "Log in",
    "lbl_email": "Email",
    "lbl_password": "Password",
    "lbl_remember_me": "Remember me",
    "btn_start_engine": "🚀 Start",
    "lbl_next_training": "Next Training",
    # Error / System messages
    "err_pwd_short": "Password too short.",
    "err_pwd_mismatch": "Passwords do not match.",
    "msg_pwd_updated": "Password updated!",
    "err_log_read": "Could not read logs",
    "err_missing_fields": "Fields missing.",
    "err_user_creation": "Could not create user",
    "err_pwd_update": "Could not update password",
    "msg_no_users_found": "No members found.",
    "err_save_manual": "Could not save.",
    "err_coach_hub": "Coach Hub error",
    "msg_session_expired": "⚠️ Session expired.",
    "msg_access_denied": "🔒 Access denied.",
    "msg_no_sessions_found": "No upcoming sessions.",
    "lbl_legend": "ℹ️ Legend",
    "tab_architect": "🏗️ Architect",
    "tab_gear": "🎒 Gear",
    "tab_exercise_bank": "📚 Exercises",
    "tab_admin": "🚫 Cancel",
    "msg_no_logs": "No logs recorded.",
    "lbl_gdpr_info_title": "Security & Privacy by Design",
    "lbl_security_storage": "Storage & Encryption",
    "txt_security_storage": "Your data is stored in the Supabase cloud using military-grade encryption (AES-256) at rest and TLS during transit.",
    "lbl_audit_logs": "Audit Trails",
    "txt_audit_logs": "The system automatically logs all database mutations (Access Logs) to guarantee integrity and detect unauthorized access.",
    "lbl_minimization": "Data Minimization",
    "txt_minimization": "We only store name, RSVP, and necessary security logs. No data is sold or shared with third parties.",
    "err_home_view": "Home screen error",
    "err_failed_to_fetch_participants": "Could not retrieve the participant list at this time.",
    "err_failed_to_fetch_buddies": "Could not retrieve available members at this time.",
    "err_rsvp_failed": "Could not update the RSVP status at this time.",
    "err_leadership_toggle_failed": "Could not change leadership status.",
    "msg_extreme_wind_alert": "⚠️ Extreme wind detected! Focus strictly on standing exercises and avoid ground-level or lightweight equipment.",
    "err_css_load_failed": "Could not successfully initialize custom application interface styles.",
    "lbl_mock_weather_desc": "Clear and sunny (Dev Mock)",
    "   lbl_weather_unavailable": "Weather data unavailable at this time",
    "   lbl_weather_rate_limited": "Weather metrics temporarily throttled",
    "err_lang_update_failed": "Could not successfully save your language selection.",
    "err_pwd_update_failed": "Password configuration change failed.",
    "err_gdpr_fetch_failed": "Could not extract data logs for dynamic compliance printing.",
    "lbl_user_id_col": "User ID",
    "lbl_display_name_col": "Display Name",
    "lbl_role_id_col": "Role ID",
    "lbl_rsvp_id_col": "RSVP ID",
    "lbl_session_id_col": "Session ID",
    "lbl_timestamp_col": "Timestamp",
    "lbl_location_col": "Location",
    "lbl_status_col": "Status",
    "lbl_was_leader_col": "Was Coach",
    "lbl_log_id_col": "Log ID",
    "lbl_operation_col": "Operation",
    "lbl_target_table_col": "Target Table",
    "lbl_target_row_col": "Target Row ID",
    "lbl_system_anon": "System / Anonymous",
    "lbl_attempt_col": "Attempt",
    "lbl_security_deviation": "SECURITY DEVIATION",
    "lbl_actor_col": "Actor",
    "lbl_modified_action": "Modified",
    "err_user_creation_failed": "Administrative user provisioning sequence failed.",
    "err_pwd_reset_failed": "Forced administrative credential reset failed.",
    "err_save_failed": "Could not successfully insert the exercise record into the databank.",
    "lbl_nameless": "Unnamed Exercise",
    "msg_login_success": "Login successful, welcome",
    "err_invalid_credentials": "Invalid login credentials. Please try again.",
    "err_profile_missing": "Login rejected: Missing user profile record",
    "lbl_cp_select_base": "Select base protocol",
    "lbl_cp_choose_exercise": "Select exercise (Bodyweight)",
    "lbl_station": "Station",
    "lbl_cp_topping": "Topping (Exercise A)",
    "lbl_cp_base": "Base (Exercise B)",
    "lbl_cp_triplet_block": "Triplet Block",
    "lbl_minutes_short": "min",
    "lbl_exercise": "Exercise",
    "err_cp_equip_clash_pre": "Equipment conflict: You are using",
    "err_cp_equip_clash_post": "different tools (Max is",
    "msg_cp_weather_floor_note": "Note: Some selected exercises are ground-based movements.",
}
