# src/lang_swe.py

TEXTS = {
    # Navigation
    "nav_home": "🏠 Hem",
    "nav_coach": "🔑 Coach",
    "nav_sessions": "📅 Pass",
    "nav_admin": "👥 Konto",
    # General UI
    "lbl_hello": "Hej",
    "lbl_member": "Medlem",
    "lbl_total": "Totalt",
    "lbl_date": "Datum",
    "lbl_time": "Tid",
    "lbl_location": "Plats",
    "lbl_wind": "Vind",
    "lbl_weather": "Väder",
    "lbl_unknown_date": "Okänt datum",
    "lbl_system": "Systemet",
    "lbl_me": "(Du)",
    "lbl_guest_coach": "Gästcoach",
    # Profile & Settings
    "lbl_profile_info": "**Här kan du hantera dina personliga inställningar, ändra språk samt hantera din säkerhet.**",
    "lbl_account_details": "Kontouppgifter",
    "lbl_full_name": "Fullständigt namn",
    "lbl_role": "Användarnivå / Roll",
    "lbl_lang_selector": "🌐 Välj systemspråk",
    "lbl_session": "Session",
    "lbl_security": "Inställningar & Säkerhet",
    "lbl_pwd_expander": "🔑 Ändra lösenord",
    "lbl_new_pwd": "Nytt lösenord",
    "lbl_conf_pwd": "Bekräfta nytt lösenord",
    "lbl_gdpr_expander": "🔒 Datasekretess & GDPR",
    "lbl_gdpr_header": "GDPR Registerutdrag",
    "lbl_gdpr_text": "Enligt dataskyddsförordningen (GDPR) har du rätt att ladda ner all persondata som finns lagrad om dig.",
    "lbl_gdpr_future": "*(Framtida funktion: Genererar en krypterad JSON-fil med dina profil-, RSVP- och träningsdata)*",
    "btn_pwd_update": "Uppdatera lösenord",
    "btn_gdpr_export": "📦 Begär GDPR-datautdrag",
    "btn_logout": "Logga ut från Coach Engine",
    # Admin & Logs
    "tab_access_logs": "📋 Access Logs",
    "tab_user_management": "👥 Användarhantering",
    "tab_system_settings": "⚙️ Systeminställningar",
    "tab_profile": "👤 Min Profil",
    "tab_stats": "📊 Statistik",
    "lbl_unknown_time": "Okänd tid",
    "lbl_modified": "modifierade",
    "btn_create_user": "➕ Skapa ny användare",
    "lbl_temp_pwd": "Temporärt lösenord (Minst 6 tecken)",
    "lbl_first_name": "Förnamn",
    "role_member": "Medlem",
    "role_coach": "Coach",
    "role_admin": "Admin",
    "lbl_system_role": "Systemroll",
    "btn_invite_user": "Bjud in och skapa konto",
    "btn_reset_pwd": "🔑 Återställ lösenord för medlem",
    "lbl_select_user": "Välj medlem att återställa",
    "lbl_new_temp_pwd": "Nytt temporärt lösenord",
    "btn_forced_reset": "Forcerat lösenordsbyte",
    "msg_admin_warning": "**Här kan du ställa in eller återaktivera det valda passet.** Detta påverkar vad som visas för deltagarna på hemskärmen omedelbart.\n\n* 🎈 **Ballongerna** bekräftar när det sparas! 🥳",
    "lbl_status": "Status:",
    "lbl_canceled": "🔴 INSTÄLLT",
    "lbl_active": "🟢 AKTIVT",
    "btn_activate": "✅ Aktivera pass",
    "btn_cancel": "🚫 Ställ in pass",
    "btn_manage": "⚙️ Hantera",
    "err_no_data": "Kunde inte läsa sessionsdata.",
    "err_status_update": "Kunde inte uppdatera status: ",
    # Stats & Weather Heroes
    "msg_stats_intro": "📊 Här samlas gruppens officiella väderhjältar baserat på genomförda pass och historiska väderdata.",
    "msg_no_stats": "Inga aktiva medlemmar eller statistik hittades just nu.",
    "lbl_my_status": "Din träningsstatus",
    "lbl_entire_squad": "Hela Elittruppen",
    "lbl_leader_small": "ledda",
    "lbl_to": "till",
    "lbl_under_10": "Pass under -10°C",
    "lbl_over_20": "Pass över +20°C",
    "lbl_bad": "Dåligt väder",
    "lbl_windy": "Blåsiga pass",
    "lbl_dark": "Mörkerpass",
    "lbl_climate_range": "Klimatspann",
    "rank_elite_veteran": "🎖️ Elit-Veteran",
    "rank_heavy_hitter": "🏋️‍♂️ Tung Kämpe",
    "rank_active_member": "🏃‍♂️ Aktiv Medlem",
    "rank_recruit": "🔰 Rekryt",
    "lbl_total_sessions": "Totalt antal pass",
    "lbl_bad_weather": "Dåligt",
    "lbl_storm": "Storm",
    "lbl_leader_caps": "Led",
    # Architect & Workout
    "msg_architect_info": "**Här bygger du träningspassets struktur.** Välj ett protokoll för att låta motorn slumpa och matcha övningar baserat på väder, geografi och nivåer.",
    "lbl_protocol": "Typ (Protokoll)",
    "lbl_levels": "Nivåer (Session Architecture)",
    "lvl_1_label": "🏃‍♂️ Nivå 1: Monostructural (Kondition, löpning & flås)",
    "lvl_2_label": "🏋️‍♂️ Nivå 2: Hybrid Structure (Basredskap, rörlighet & styrka)",
    "lvl_3_label": "🏁 Nivå 3: Multi-Segment / 'The Gauntlet' (Tunga redskap & stationer)",
    "lbl_equip_filter": "Utrustningsfilter",
    "lbl_bodyweight_only": "🤸‍♂️ Endast kroppsvikt",
    "lbl_manual_notes": "📝 Manuella noteringar (Tips/Instruktioner)",
    "ph_manual_notes": "Skriv passets upplägg eller instruktioner här...",
    "btn_generate_suggestion": "🚀 Generera förslag",
    "btn_save_manual": "💾 Spara manuellt pass / notering",
    "lbl_architect_summary": "Arkitektens Sammanfattning",
    "lbl_duration": "Tid",
    "lbl_stations": "Stationer",
    "lbl_rounds": "Ronder",
    "lbl_work_sec": "Jobb (s)",
    "lbl_blocks": "Block",
    "lbl_rest_sec": "Vila (s)",
    "lbl_minutes": "Min",
    "msg_no_session": "Inget pass har genererats ännu.",
    "lbl_todays_session": "Dagens pass",
    "lbl_simplified_exercise": "💡 förenklad övning",
    "lbl_coach_notes": "📝 Coachens noteringar",
    "lbl_equipment_list": "🎒 🪵 Materiallista 🪨 ⛓️",
    "btn_publish": "Publicera & Spara till Elittruppen",
    "lbl_select_session": "Välj pass att hantera",
    "msg_legend_details": (
        "✅ **Tomt** – Helt orört pass, redo att planeras!\n"
        "🏗️ **Övningar** – Endast träningsprogram/block är skapade.\n"
        "🎒 **Material** – Endast packlista/material är beställt.\n"
        "📝 **Notering** – Endast en manuell notering finns sparad.\n"
        "📚 **Kombination** – Innehåller en mix av övningar, material eller noteringar.\n"
        "🚫 **Inställt** – Passet är inställt för deltagarna."
    ),
    "msg_suggestion_generated": "💡 Förslag genererat baserat på aktuellt väder!",
    "msg_architect_thinking": "🧠 Arkitekten analyserar miljödata...",
    # Gear & Exercises
    "msg_gear_info": "**Hantering av bärbar utrustning.** Välj ut utrusting. Denna lista kan uppdateras oberoende eller som ett komplement till ett inplanerat pass.",
    "lbl_standard": "Standard",
    "msg_save_confirmation": "🎈 Ballongerna bekräftar när det sparas! 🥳 Inga ballonger = försök spara en gång till!",
    "btn_lock_gear": "Lås materialbeställning",
    "msg_bank_info": "**Globalt övningsbibliotek.** Det är från den här banken som Arkitekten hämtar byggstenar till passen.",
    "btn_contribute_exercise": "➕ Bidra med ny övning",
    "lbl_exe_name": "Övningens namn",
    "lbl_instructions": "Instruktioner",
    "lbl_equipment": "Utrustning",
    "lbl_level": "Nivå",
    "lbl_standing": "Stående",
    "lbl_rain": "Regn",
    "lbl_hill": "Backe",
    "lbl_wall": "Mur / Trappa",
    "btn_save_bank": "Spara i banken",
    "msg_saved": "Sparat!",
    "msg_bank_empty": "Tomt i banken eller kunde inte hämta data.",
    "lbl_bodyweight": "Egenvikt",
    "lbl_search_exe": "Sök övning:",
    "btn_clear_search": "❌ Rensa sökning",
    "lbl_showing": "Visar",
    "lbl_exercises": "övningar",
    # Sessions & Home
    "lbl_good_morning": "God morgon",
    "lbl_good_evening": "God kväll",
    "msg_no_sessions": "Inga kommande pass inplanerade just nu.",
    "lbl_session_canceled": "PASS INSTÄLLT",
    "msg_home_instructions": "**Nästa träningspass!** För samtliga pass, se **pass** fliken.",
    "err_home_view": "Hemskärmsfel",
    "btn_attending": "✅ Kommer",
    "btn_take_crown": "👑 Ta spiran",
    "btn_cant_make_it": "❌ Kan inte",
    "btn_step_down": "👑👋 Abdikera",
    "msg_session_admin_info": "Här kan du administrera deltagande på alla framtida pass, se historik (de senaste 20), samt lägga till nya pass i kalendern.",
    "tab_upcoming": "📅 Kommande",
    "tab_history": "📜 Historik",
    "tab_create_session": "➕ Skapa nytt pass",
    "msg_no_upcoming": "Inga planerade pass just nu.",
    "lbl_registered": "anmälda",
    "lbl_participants": "Deltagare",
    "lbl_cant_make_it": "Kan inte",
    "msg_no_history": "Ingen historik hittades.",
    "lbl_who_was_there": "Vilka var där",
    "btn_save_session": "Spara pass",
    "msg_session_created": "Passet har skapats!",
    "msg_leader_secured": "✅ **Spiran är säkrad!**",
    "msg_leader_needed": "⚠️ **Tronen står tom!** Vem axlar ansvaret att leda passet?",
    "btn_register_buddy": "➕ Anmäl en kompis",
    "btn_book_buddy": "👥 Boka träningskompis",
    "placeholder_select_member": "Välj medlem...",
    "lbl_attending": "Anmälda",
    "lbl_not_coming": "Kan inte",
    "msg_no_registrations": "Inga anmälda deltagare.",
    # Landing
    "msg_landing_welcome": "**Elittruppen i Rönninge.** Kompisträning två gånger i veckan. Helt kostnadsfritt.",
    "msg_landing_details": "Alla kan vara med, kom som du är.",
    "lbl_schedule": "**Onsdagar** kl 18.00 \n\n**Söndagar** kl 09.30",
    "lbl_login": "Logga in",
    "lbl_email": "E-post",
    "lbl_password": "Lösenord",
    "lbl_remember_me": "Kom ihåg mig",
    "btn_start_engine": "🚀 Starta motorn",
    "lbl_next_training": "Nästa träning",
    # System/Error
    "msg_session_expired": "⚠️ Sessionen har utgått.",
    "msg_access_denied": "🔒 Åtkomst nekad.",
    "msg_no_sessions_found": "Inga kommande pass.",
    "lbl_legend": "ℹ️ Ikonförklaring (Legend)",
    "tab_architect": "🏗️ Arkitekt",
    "tab_gear": "🎒 Material",
    "tab_exercise_bank": "📚 Övningar",
    "tab_admin": "🚫 Ställ in",
    "msg_no_logs": "Inga loggar.",
    "lbl_gdpr_info_title": "Säkerhet & Inbyggt Dataskydd",
    "lbl_security_storage": "Lagring & Kryptering",
    "txt_security_storage": "Din data lagras i Supabase-molnet med militärliknande kryptering (AES-256) vid vila och TLS vid överföring.",
    "lbl_audit_logs": "Spårbarhet",
    "txt_audit_logs": "Systemet loggar automatiskt alla databasändringar (Access Logs) för att garantera integritet och upptäcka obehörig åtkomst.",
    "lbl_minimization": "Dataminimering",
    "txt_minimization": "Vi sparar endast namn, RSVP och nödvändiga säkerhetsloggar. Inga data säljs eller delas med tredje part.",
    "err_coach_hub": "Fel i Coach Hub",
    "err_log_read": "Kunde inte läsa loggarna",
    "err_missing_fields": "Alla fält måste fyllas i.",
    "err_pwd_mismatch": "Lösenorden matchar inte.",
    "err_pwd_short": "Lösenordet är för kort.",
    "err_pwd_update": "Kunde inte uppdatera lösenordet",
    "err_save_manual": "Kunde inte spara.",
    "err_user_creation": "Kunde inte skapa användare",
    "msg_no_users_found": "Inga medlemmar hittades.",
    "msg_pwd_updated": "Lösenordet har uppdaterats!",
    "err_failed_to_fetch_participants": "Kunde inte hämta deltagarlistan just nu.",
    "err_failed_to_fetch_buddies": "Kunde inte hämta lediga medlemmar just nu.",
    "err_rsvp_failed": "Det gick inte att uppdatera anmälningsstatusen just nu.",
    "err_leadership_toggle_failed": "Kunde inte ändra ledarstatus.",
    "msg_extreme_wind_alert": "⚠️ Extrem vind detekterad! Fokusera på stående övningar och undvik liggande övningar samt lätta tillbehör.",
    "err_css_load_failed": "Det gick inte att ladda applikationens anpassade designstilar.",
    "lbl_mock_weather_desc": "Klart och soligt (Dev Mock)",
    "lbl_weather_unavailable": "Väderdata ej tillgänglig",
    "lbl_weather_rate_limited": "Väderdata tillfälligt begränsad",
    "err_lang_update_failed": "Det gick inte att spara ditt språkval.",
    "err_pwd_update_failed": "Lösenordsuppdateringen misslyckades.",
    "err_gdpr_fetch_failed": "Kunde inte hämta användardata för registerutdrag.",
    "lbl_user_id_col": "Användar ID",
    "lbl_display_name_col": "Visningsnamn",
    "lbl_role_id_col": "Systemroll ID",
    "lbl_rsvp_id_col": "Anmälnings ID",
    "lbl_session_id_col": "Pass ID",
    "lbl_timestamp_col": "Tidsstämpel",
    "lbl_location_col": "Plats",
    "lbl_status_col": "Status",
    "lbl_was_leader_col": "Var Passledare",
    "lbl_log_id_col": "Logg ID",
    "lbl_operation_col": "Operation",
    "lbl_target_table_col": "Måltabell",
    "lbl_target_row_col": "Mål Rad ID",
    "lbl_system_anon": "System / Anon",
    "lbl_attempt_col": "Försök",
    "lbl_security_deviation": "SÄKERHETSAVVIKELSE",
    "lbl_actor_col": "Aktör",
    "lbl_modified_action": "Modifierade",
    "err_user_creation_failed": "Det gick inte att registrera användaren.",
    "err_pwd_reset_failed": "Det gick inte att återställa lösenordet.",
    "err_save_failed": "Det gick inte att spara övningen i databanken.",
    "lbl_nameless": "Namnlös övning",
    "msg_login_success": "Inloggningen lyckades, välkommen",
    "err_invalid_credentials": "Felaktiga inloggningsuppgifter. Vänligen försök igen.",
    "err_profile_missing": "Inloggning avvisad: Saknar användarprofil",
    "lbl_cp_select_base": "Välj bas-protokoll",
    "lbl_cp_choose_exercise": "Välj övning (Egenvikt)",
    "lbl_station": "Station",
    "lbl_cp_topping": "Topping (Övning A)",
    "lbl_cp_base": "Base (Övning B)",
    "lbl_cp_triplet_block": "Triplet Block",
    "lbl_minutes_short": "min",
    "lbl_exercise": "Övning",
    "err_cp_equip_clash_pre": "Utrustningskonflikt: Du använder",
    "err_cp_equip_clash_post": "olika redskap (Max är",
    "msg_cp_weather_floor_note": "Notera: Vissa valda övningar är liggande övningar.",
    "msg_status_synced": "Status har uppdaterats globalt!",
}
